spring.application.name=api
# URL de la base (Adresse + Port + Nom de la base)
spring.datasource.url=jdbc:mysql://localhost:3306/chatop

# Appel des variables Windows (rien n'est écrit en clair ici !)
spring.datasource.username=${DB_CHATOP_USER}
spring.datasource.password=${DB_CHATOP_PASSWORD}

spring.jpa.show-sql=true